version: "3.8"
services:
  app:
    container_name: "sbcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
    
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/db_postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Cu213lona1993
    
    depends_on:
    
      - postgres_db
   
  postgres_db:
    container_name: "postgres_db"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Cu213lona1993"
      POSTGRES_DB: "db_postgres"
volumes:
  postgres-data:
